(() => {
'use strict';
const FW=window.FolioWishStudio,$=s=>document.querySelector(s);
const pageDefaults=type=>{
 const id=FW.uid(),photos={};
 if(type==='cover')return{id,type,headline:'HAPPY BIRTHDAY',subline:'THE BIRTHDAY ISSUE',bubble:'Made with love.',side:'MEMORIES\nINSIDE',photos};
 if(type==='profile')return{id,type,headline:'Meet the cover star',quote:'A person worth a whole issue.',facts:['Current obsession','Known for','Perfect day','Next chapter'],photos};
 if(type==='reasons')return{id,type,headline:'Reasons you deserve the cover',reasons:['You show up','You make us laugh','You notice the small things','You make ordinary days better','You are deeply yourself','We are lucky to know you'],photos};
 if(type==='gallery')return{id,type,headline:'The camera roll',note:'The blurry ones are usually the best memories.',photos};
 if(type==='letter')return{id,type,headline:'A letter for your next chapter',body:'Happy birthday.\n\nHere is to more good days, brave choices, ridiculous stories and people who let you be fully yourself.',sign:'With love',photos};
 if(type==='timeline')return{id,type,headline:'The story so far',items:[['Then','Where the story begins.'],['Now','A chapter worth remembering.'],['Next','More good things ahead.']],photos};
 if(type==='playlist')return{id,type,headline:'The soundtrack',tracks:['Road-trip opener','Current obsession','The throwback','Late-night song','Main-character song'],photos};
 return{id,type:'backcover',headline:'Here’s to the next story.',body:'Keep the good parts. Keep becoming more yourself.',photos};
};
FW.addPage=type=>{FW.project.pages.splice(FW.project.active+1,0,pageDefaults(type));FW.project.active++;FW.renderAll();};
FW.smartFill=()=>{const p=FW.project.person,name=(p.name||'You').trim()||'You',age=(p.age||'').trim(),rel=p.relationship||'Friend',mem=(p.memory||'').trim()||'small adventures, big laughs, and stories worth keeping',vibe=p.vibe||'warm';const adj={fun:['chaotic in the best way','impossibly funny','always ready for the plot twist','a certified good-time person'],editorial:['effortlessly memorable','quietly magnetic','impossible to copy','always worth the cover'],minimal:['kind','steady','curious','completely yourself'],warm:['generous','funny','thoughtful','braver than you know']}[vibe]||['generous','funny','thoughtful','braver than you know'];
 const find=t=>FW.project.pages.find(x=>x.type===t);let x=find('cover');if(x){x.headline='HAPPY BIRTHDAY';x.subline=`THE ${age?age+'TH ':''}BIRTHDAY ISSUE`;x.bubble=`${name}, this one is all about you.`;x.side=`${rel.toUpperCase()} EDITION\nMEMORIES INSIDE`;}
 x=find('profile');if(x){x.headline=`Meet ${name}, our cover star`;x.quote=`${name} is ${adj[0]} — and the easiest person to build a whole issue around.`;x.facts=[adj[1],adj[2],mem.slice(0,70),adj[3]];}
 x=find('reasons');if(x){x.headline=`${age||18} reasons ${name} deserves the cover`;x.reasons=[`You are ${adj[0]}`,`You are ${adj[1]}`,`You are ${adj[2]}`,'You make people feel welcome','You turn small plans into memories','You know when to listen','You celebrate other people','You can laugh at yourself','You make boring days better','You keep going after hard weeks','You care about tiny details','You bring your own point of view','You make people feel remembered','You are growing without losing yourself','You make space for joy','You have excellent story material','You are deeply loved','There is nobody else quite like you'].slice(0,Math.min(18,Number(age)||18));}
 x=find('gallery');if(x){x.headline=`The ${name} camera roll`;x.note=mem;}
 x=find('timeline');if(x){x.headline=`The story of ${name}, so far`;x.items=[['The beginning',`Before this issue had a cover, ${name} was already becoming the person everyone knows now.`],['A favorite memory',mem],['Right now',`${name} at ${age||'this age'}: ${adj[0]}, ${adj[1]}, and still surprising us.`],['Next chapter','More stories, better photos, and at least one plan that gets slightly out of hand.']];}
 x=find('playlist');if(x){x.headline=`Songs that sound like ${name}`;x.tracks=['The road-trip opener','The scream-the-chorus song','The current obsession','The impossible-to-skip throwback','The late-night drive song','The one that feels like summer'];}
 x=find('letter');if(x){x.headline=`For ${name}, on the next page`;x.body=`Happy birthday, ${name}.\n\nI hope this next year gives you more moments that feel like ${mem.toLowerCase()}. I hope you keep the people who let you be fully yourself, take the chances that make the story better, and leave room for quiet days too.\n\nThank you for being ${adj[0]}, ${adj[1]}, and entirely your own person. The best part is that there is still so much ahead.`;x.sign=`With love, your ${rel.toLowerCase()}`;}
 x=find('backcover');if(x){x.headline=`Keep the good parts, ${name}.`;x.body='The best issue is the life you are still making.';}FW.renderAll();};
FW.compressImage=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{let{width,height}=img,max=1600;if(Math.max(width,height)>max){const s=max/Math.max(width,height);width=Math.round(width*s);height=Math.round(height*s);}const c=document.createElement('canvas');c.width=width;c.height=height;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,width,height);resolve(c.toDataURL('image/jpeg',.82));};img.onerror=reject;img.src=reader.result;};reader.onerror=reject;reader.readAsDataURL(file);});
const backup=()=>{const blob=new Blob([JSON.stringify(FW.project,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`foliowish-${(FW.project.person.name||'birthday').toLowerCase().replace(/[^a-z0-9]+/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);};
FW.boot=()=>{
 const qTheme=new URLSearchParams(location.search).get('theme');if(qTheme&&FW.themes[qTheme])FW.project.theme=qTheme;
 const map={personName:'name',age:'age',relationship:'relationship',vibe:'vibe',memory:'memory'};Object.keys(map).forEach(id=>$('#'+id)?.addEventListener('input',e=>{FW.project.person[map[id]]=e.target.value;FW.renderCurrent();FW.renderThumbs();FW.renderChecks();FW.save();}));
 $('#smartFillBtn').onclick=FW.smartFill;$('#mobileSmartFill').onclick=FW.smartFill;
 $('#duplicateBtn').onclick=()=>{const cp=FW.clone(FW.project.pages[FW.project.active]);cp.id=FW.uid();FW.project.pages.splice(FW.project.active+1,0,cp);FW.project.active++;FW.renderAll();};
 $('#deleteBtn').onclick=()=>{if(FW.project.pages.length<=1){alert('A magazine needs at least one page.');return;}if(confirm('Delete this page?')){FW.project.pages.splice(FW.project.active,1);FW.project.active=Math.max(0,FW.project.active-1);FW.renderAll();}};
 $('#moveLeftBtn').onclick=()=>{const i=FW.project.active;if(i<=0)return;[FW.project.pages[i-1],FW.project.pages[i]]=[FW.project.pages[i],FW.project.pages[i-1]];FW.project.active--;FW.renderAll();};
 $('#moveRightBtn').onclick=()=>{const i=FW.project.active;if(i>=FW.project.pages.length-1)return;[FW.project.pages[i+1],FW.project.pages[i]]=[FW.project.pages[i],FW.project.pages[i+1]];FW.project.active++;FW.renderAll();};
 $('#zoomIn').onclick=()=>{FW.project.zoom=Math.min(1.05,FW.project.zoom+.06);FW.renderCurrent();FW.save(false);};$('#zoomOut').onclick=()=>{FW.project.zoom=Math.max(.35,FW.project.zoom-.06);FW.renderCurrent();FW.save(false);};
 $('#fitBtn').onclick=()=>{const w=$('.stage-wrap').clientWidth-80,h=$('.stage-wrap').clientHeight-190;FW.project.zoom=Math.max(.35,Math.min(.92,w/595,h/842));FW.renderCurrent();FW.save(false);};$('#safeBtn').onclick=()=>{FW.safeVisible=!FW.safeVisible;FW.renderCurrent();};
 $('#undoBtn').onclick=()=>FW.restoreHistory(FW.historyIndex-1);$('#redoBtn').onclick=()=>FW.restoreHistory(FW.historyIndex+1);$('#backupBtn').onclick=backup;
 $('#importProject').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(p?.version!==1||!Array.isArray(p.pages))throw 0;FW.project=p;FW.syncInputs();FW.renderAll();}catch{alert('That does not look like a FolioWish project file.');}};r.readAsText(f);e.target.value='';};
 $('#photoInput').onchange=async e=>{const file=e.target.files?.[0];if(!file||!FW.pendingPhotoSlot)return;if(file.size>15*1024*1024){alert('Please choose an image under 15 MB.');return;}try{const data=await FW.compressImage(file),page=FW.project.pages[FW.project.active];page.photos ||= {};page.photos[FW.pendingPhotoSlot]=data;FW.renderAll();}catch{alert('Could not read that image. Try JPG, PNG or WebP.');}finally{e.target.value='';FW.pendingPhotoSlot=null;}};
 $('#exportBtn').onclick=()=>{const print=$('#printArea');print.innerHTML=FW.project.pages.map(p=>`<section class="print-page">${FW.renderPage(p,false)}</section>`).join('');setTimeout(()=>window.print(),120);};
 document.querySelectorAll('[data-drawer]').forEach(b=>b.onclick=()=>$('#'+b.dataset.drawer).classList.add('open'));document.querySelectorAll('[data-close-drawer]').forEach(b=>b.onclick=()=>b.closest('.mobile-drawer').classList.remove('open'));
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();backup();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();FW.restoreHistory(FW.historyIndex-1);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();FW.restoreHistory(FW.historyIndex+1);}});
 if(innerWidth<=820)FW.project.zoom=Math.min(FW.project.zoom,Math.max(.48,(innerWidth-34)/595));addEventListener('resize',()=>{if(innerWidth<=820){const z=Math.max(.48,(innerWidth-34)/595);if(FW.project.zoom>z){FW.project.zoom=z;FW.renderCurrent();}}});
 FW.renderLibrary();FW.syncInputs();FW.renderAll(false);FW.save(false);
};
})();
